require("dotenv").config();
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const path = require("path");
const fs = require("fs");
const fetch = require("node-fetch");
const bodyParser = require("body-parser");
const pool = require("./config/db");

const app = express();
const port = process.env.PORT || 3000;

const allowedOrigins = [
  "https://ricevault.shop",
  "https://ricedeployment2.onrender.com",
  "http://localhost:3001", // Dev frontend
];

// Enable CORS
app.use(cors({
  origin: allowedOrigins,
  credentials: true,
}));

// CSP with helmet
app.use(helmet());
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      defaultSrc: ["'self'"],
      connectSrc: ["'self'", "https://ricevault.shop", "https://ricedeployment2.onrender.com", "https://openrouter.ai"],
      scriptSrc: ["'self'", "'unsafe-inline'"],
      styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
      fontSrc: ["'self'", "https://fonts.gstatic.com"],
      imgSrc: ["'self'", "data:"],
      objectSrc: ["'none'"],
    },
  })
);

// Body parsing
app.use(express.json());
app.use(bodyParser.json());

// Token check
const verifyToken = require("./middleware/verifyToken");

// Routes
const authRoutes = require("./auth");
const customerRoutes = require("./routes/customers");
const storageRoutes = require("./routes/storage");
const millRoutes = require("./routes/mills");
const profitRoutes = require("./routes/profits");
const transactionRoutes = require("./routes/transactions");

// Logging for debug
app.use((req, res, next) => {
  console.log(`[${req.method}] ${req.url}`);
  next();
});
if (process.env.NODE_ENV === "production") {
  app.use(express.static(path.join(__dirname, "Client/build")));
}
// Auth route (no token required)
app.use("/api/auth", authRoutes);

// Protected routes (token required)
app.use("/", verifyToken, customerRoutes);
app.use("/", verifyToken, storageRoutes);
app.use("/", verifyToken, millRoutes);
app.use("/", verifyToken, profitRoutes);
app.use("/", verifyToken, transactionRoutes);

// Serve frontend


// Chatbot route
app.post("/api/chatbot", verifyToken, async (req, res) => {
  try {
    const userQuestion = req.body.query;
    const schema = fs.readFileSync("dbSchema.txt", "utf8");

    // 🔎 Debug logs
    console.log("User asked:", userQuestion);
    console.log(
      "🔑 API Key loaded?",
      process.env.OPENROUTER_API_KEY ? "✅ YES" : "❌ NO"
    );
    console.log("🤖 Model:", process.env.OPENROUTER_MODEL_NAME);
    console.log("📩 Headers being sent:", {
      Authorization: process.env.OPENROUTER_API_KEY
        ? "Bearer [HIDDEN]"
        : "MISSING",
      "Content-Type": "application/json",
    });

    const prompt = `You are an intelligent SQL generator bot. 
    Use the following database schema to answer questions:
    ${schema}
    
    Question: ${userQuestion}
    Respond with a valid SQL query and nothing else.`;

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: process.env.OPENROUTER_MODEL_NAME,
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("❌ OpenRouter API Error:", errorText);
      return res
        .status(response.status)
        .json({ error: "Failed to fetch from OpenRouter", details: errorText });
    }

    const data = await response.json();
    const sqlQuery = data.choices?.[0]?.message?.content?.trim();

    if (!sqlQuery) {
      return res
        .status(500)
        .json({ error: "No SQL query generated by the model" });
    }

    res.json({ query: sqlQuery });
  } catch (err) {
    console.error("🔥 Chatbot error:", err.message);
    res.status(500).json({ error: "Internal server error" });
  }
});
app.get("*", (req, res) => {
    res.sendFile(path.join(__dirname, "Client/build", "index.html"));
  });
// Start server
app.listen(port, () => {
  console.log(`🚀 Server running on port ${port}`);
});
